// 'HITS'
export const ADD_HITS_ITEMS_SUCCESS = 'ADD_HITS_ITEMS_SUCCESS';
export const HITS_LOADER_START = 'HITS_LOADER';
export const HITS_LOADER_ERROR = 'HITS_LOADER_ERROR';

export const ADD_CATALOG_SUCCES = 'ADD_HITS_ITEMS_SUCCESS';
export const CATALOG_LOADER_START = 'CATALOG_LOADER_START';
export const CATALOG_LOADER_ERROR = 'CATALOG_LOADER_ERROR';
