// 'HITS'
export const ADD_HITS_ITEMS_SUCCESS = 'ADD_HITS_ITEMS_SUCCESS';
export const HITS_LOADER_START = 'HITS_LOADER';
export const HITS_LOADER_ERROR = 'HITS_LOADER_ERROR';

export const ADD_CATALOG_SUCCES = 'ADD_HITS_ITEMS_SUCCESS';
export const CATALOG_LOADER_START = 'CATALOG_LOADER_START';
export const CATALOG_LOADER_ERROR = 'CATALOG_LOADER_ERROR';
export const CLEAR_CATALOG = 'CLEAN_CATALOG';

export const ADD_CATEGORIES_SUCCES = 'ADD_CATEGORIES_SUCCES';
export const CATEGORIES_LOADER_START = 'CATEGORIES_LOADER_START';
export const CATEGORIES_LOADER_ERROR = 'CATEGORIES_LOADER_ERROR';

export const ADD_FORM_VALUES = 'ADD_FORM_VALUES';
export const CLEAR_FORM = 'CLEAR_FORM';

export const ADD_CARD_ITEM_SUCCES = 'ADD_CARD_ITEM';
export const CARD_LOADER_START = 'CARD_LOADER_ITEM';
export const CARD_LOADER_ERROR = 'CARD_LOADER_ERROR';
